apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-deploy-demo-stage
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Ritesh205/k8s-deploy-demo.git
    targetRevision: deploy
    path: helm/k8s-deploy-demo
    helm:
      valueFiles:
        - values.yaml
        - values-stage.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: stage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
