apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-deploy-demo-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Ritesh205/k8s-deploy-demo.git
    targetRevision: deploy
    path: helm/k8s-deploy-demo
    helm:
      valueFiles:
        - values.yaml
        - values-prod.yaml
      parameters:
        - name: image.tag
          value: ""  # This will be overridden by values file
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
    - group: ""
      kind: Service
      jsonPointers:
        - /spec/clusterIP
    # Additional prod-specific ignore differences
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/strategy  # Ignore deployment strategy changes in prod
