# Production environment values
environment: prod
replicaCount: 1

image:
  tag: "sha-4fe6f2392c7ac182c8d0541cd2b76cba400389bb"

service:
  nodePort: 30082

resources:
  requests:
    cpu: 1000m
    memory: 2Gi
  limits:
    cpu: 2000m
    memory: 4Gi

springProfile: prod

configMap:
  LOG_LEVEL: WARN

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80
