# Development environment values
environment: dev
replicaCount: 1

image:
  tag: "sha-a12a5cd3738a16b3a88aaa49ba764279a3739964"

service:
  nodePort: 30080

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

springProfile: dev

configMap:
  LOG_LEVEL: DEBUG
