# Production environment values
environment: prod
replicaCount: 1

image:
  tag: "sha-b780a9a50532aed9a19cf85a87ec8d08150d4a7b"

service:
  nodePort: 30082

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

springProfile: prod

configMap:
  LOG_LEVEL: WARN

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80
