# Staging environment values
environment: stage
replicaCount: 1

image:
  tag: "sha-2683f9c8d061bc7812b627d65fff1d679c0ba3bd"

service:
  nodePort: 30081

resources:
  requests:
    cpu: 500m
    memory: 1Gi
  limits:
    cpu: 1000m
    memory: 2Gi

springProfile: stage

configMap:
  LOG_LEVEL: INFO
