# Production environment values
environment: prod
replicaCount: 1

image:
  tag: "sha-239e219a1cfceb505584a859bc24d8ddbc804b33"

service:
  nodePort: 30082

resources:
  requests:
    cpu: 1000m
    memory: 2Gi
  limits:
    cpu: 2000m
    memory: 4Gi

springProfile: prod

configMap:
  LOG_LEVEL: WARN

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80
