# Development environment values
environment: dev
replicaCount: 1

image:
  tag: "sha-3777edb6706cd21e85c8a1a8e0cc773bd7fee724"

service:
  nodePort: 30080

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 1Gi

springProfile: dev

configMap:
  LOG_LEVEL: DEBUG
