# Production environment values
environment: prod
replicaCount: 1

image:
  tag: "sha-7aa45626b0030b036cd5c343ebe4854f228af296"

service:
  nodePort: 30082

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

springProfile: prod

configMap:
  LOG_LEVEL: WARN

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80
