# Common values for all environments
nameOverride: ""
fullnameOverride: ""

image:
  repository: k8s-deploy-demo
  pullPolicy: Never

service:
  type: NodePort
  port: 8080

# Health check probes
livenessProbe:
  initialDelaySeconds: 60
  periodSeconds: 10
  failureThreshold: 3

readinessProbe:
  initialDelaySeconds: 30
  periodSeconds: 10
  failureThreshold: 3

# Default autoscaling configuration
autoscaling:
  enabled: false
