name: CI-CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  TAG: sha-${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build and Test
        run: ./mvnw clean verify

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Normalize image name
        run: echo "IMAGE_NAME=$(echo '${{ env.IMAGE_NAME }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}

  deploy-dev:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: deploy   # ✅ checkout deploy branch

      - name: Update Helm values for dev
        run: |
          sed -i "s|tag:.*|tag: \"${{ env.TAG }}\"|" ./helm/k8s-deploy-demo/values-dev.yaml
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add ./helm/k8s-deploy-demo/values-dev.yaml
          git commit -m "Deploy dev with image ${{ env.TAG }} [skip ci]" || echo "No changes"
          git push origin deploy

  deploy-stage:
    runs-on: ubuntu-latest
    needs: deploy-dev
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: deploy   # ✅ checkout deploy branch

      - name: Update Helm values for stage
        run: |
          sed -i "s|tag:.*|tag: \"${{ env.TAG }}\"|" ./helm/k8s-deploy-demo/values-stage.yaml
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add ./helm/k8s-deploy-demo/values-stage.yaml
          git commit -m "Deploy stage with image ${{ env.TAG }} [skip ci]" || echo "No changes"
          git push origin deploy

  deploy-prod:
    runs-on: ubuntu-latest
    needs: deploy-stage
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: deploy   # ✅ checkout deploy branch

      - name: Update Helm values for prod
        run: |
          sed -i "s|tag:.*|tag: \"${{ env.TAG }}\"|" ./helm/k8s-deploy-demo/values-prod.yaml
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add ./helm/k8s-deploy-demo/values-prod.yaml
          git commit -m "Deploy prod with image ${{ env.TAG }} [skip ci]" || echo "No changes"
          git push origin deploy
